---
- name: Add GitLab apt key
  apt_key:
    url: https://packages.gitlab.com/gpg.key
    state: present

- name: Install GitLab Runner dependencies
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - debian-archive-keyring
    - apt-transport-https
    - ca-certificates

- name: Add GitLab Runner apt repo
  apt_repository:
    repo: '{{ item }}'
    state: present
    filename: 'gitlab-runner'
  with_items:
    - "deb https://packages.gitlab.com/runner/gitlab-ci-multi-runner/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main"
    - "deb-src https://packages.gitlab.com/runner/gitlab-ci-multi-runner/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main"

- name: Install GitLab Runner
  apt:
    name: gitlab-ci-multi-runner
    state: latest
    update_cache: true

- name: Setup gitlab-runner directories
  include: setup-dirs.yml

- name: Copy config.toml
  template:
    src: config.toml.j2
    dest: "/etc/gitlab-runner/config.toml"
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Install Self-Signed cert on system
  include: custom-certs.yml
  when: gitlab_runner_coordinator_cert_path != ''

- name: Wait untils Gitlab web API is available
  shell: curl --head --insecure --silent '{{ gitlab_runner_coordinator_url }}'
  register: result
  until: result.stdout.find("302 Found") != -1
  retries: 12
  delay: 5

- name: Register GitLab Runner
  include: register-runner.yml
  when: gitlab_runner_registration_token != ''
